### ISSUE TITLE
DBDiff does not work for me

### ISSUE THREAD

**Issue by amontalban** [DBDiff/DBDiff#18]
Hey,

I'm trying DBDiff to see if we can use it in our push to production process and I can't get it to work:

```bash
root@47db20dcad75:/DBDiff# ./dbdiff --debug --server1=root:secret@192.168.1.5:32789 --server2=root:secret@192.168.1.5:32790 --type=all server1.employees:server2.employees
✖ Can't connect to target database
```

It seems that it fails to connect (I also tried by creating .dbdiff config file with following content):

```yaml
server1-user: root
server1-password: secret
server1-port: 32789
server1-host: 192.168.1.5
server2-user: root
server2-password: secret
server2-port: 32790
server2-host: 192.168.1.5
template: templates/simple-db-migrate.tmpl
type: all
include: all
no-comments: true
```

But as you can see the MySQL client can connect just fine to both servers (Docker instances):

```bash
root@47db20dcad75:/DBDiff# mysql -h 192.168.1.5 -u root -psecret -P32789 -e "show databases; select @@hostname;"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| employees          |
| mysql              |
| performance_schema |
+--------------------+
+--------------+
| @@hostname   |
+--------------+
| 9b76c1977e66 |
+--------------+
```

```bash
root@47db20dcad75:/DBDiff# mysql -h 192.168.1.5 -u root -psecret -P32790 -e "show databases; select @@hostname;"                                                                                                                              
+--------------------+
| Database           |
+--------------------+
| information_schema |
| employees          |
| mysql              |
| performance_schema |
+--------------------+
+--------------+
| @@hostname   |
+--------------+
| 2601fdf05b85 |
+--------------+
```

Am I missing something?
